Variant 7
frontend-park-mail-ru/homework_2020_2 pull request #16
Opened 2020-09-03 00:02 UTC by Scotfarel

Zakharov Ivan, APO-21 :)

2020-09-03 00:03 UTC, Scotfarel commented
Доброго времени суток!
Сделал нулевое ДЗ, 7 вариант.

2020-09-04 19:41 UTC, zelflod requested changes
Приветствую на крутом курсе фронтенда! 

Круто что знаешь про методы массивов, однако нужно выбрать оптимальный из них для решения

Когда поправишь, пиши в телегу zelflod

2020-09-04 19:41 UTC, zelflod commented on source/plain.js
> +const plain = function flatten(arr) {
Любишь смешивать?) Существует несколько способов создания функции, Function Declaration и Function Expression.  Выбери одно. Перед тем как менять свой код посмотри что находится в `console.log(plain.name)`

Можешь попробовать функции!)

2020-09-04 19:41 UTC, zelflod commented on source/plain.js
> +    return arr.reduce(function (flat, toFlatten) {
Что если `arr` не массив? Нужно на этот случай добавить тесткейс в `tests/plain.js` на некорректный ввод, а в функции добавить проверку входного значения.

2020-09-04 19:41 UTC, zelflod commented on source/plain.js
> +      return flat.concat(Array.isArray(toFlatten) ? flatten(toFlatten) : toFlatten);
`concat ` не самый оптимальный способ объединения массивов

https://dev.to/uilicious/javascript-array-push-is-945x-faster-than-array-concat-1oki

2020-09-04 19:41 UTC, zelflod commented on source/plain.js
> +const plain = function flatten(arr) {
Давай добавим jsdoc

2020-09-05 18:01 UTC, Scotfarel commented on source/plain.js
> +const plain = function flatten(arr) {
Имя у `plain` было `flatten`, теперь буду знать)

2020-09-06 14:11 UTC, Scotfarel commented on source/plain.js
> +const plain = function flatten(arr) {
Попробовал стрелочные функции, сделал однострочник)

2020-09-06 14:11 UTC, Scotfarel commented on source/plain.js
> +    return arr.reduce(function (flat, toFlatten) {
Добавил проверку типов

2020-09-06 14:12 UTC, Scotfarel commented on source/plain.js
> +const plain = function flatten(arr) {
Добавил jsdoc

2020-09-06 14:12 UTC, Scotfarel commented on source/plain.js
> +      return flat.concat(Array.isArray(toFlatten) ? flatten(toFlatten) : toFlatten);
Использовал flat()

2020-09-06 18:27 UTC, zelflod approved these changes

2020-09-08 07:33 UTC, closed without merging