ДЗ0 Письменный Даниил
frontend-park-mail-ru/homework_2020_2 pull request #8
Opened 2020-09-01 16:38 UTC by Kudesnjk

2020-09-01 16:42 UTC, Kudesnjk commented
Реализована функция set

2020-09-02 15:37 UTC, StealthTech requested changes
Привет и добро пожаловать на курс фронтенда! Мы с командой менторов и преподавателей постараемся сделать так, чтобы за полгода ты смог почерпнуть все необходимые знания, чтобы без тени сомнения мог называть себя фронтенд-разработчиком!

Я нашел несколько мест, требующих внимания и внесения исправлений. Пожалуйста, посмотри и постарайся поправить. Если будут вопросы — обращайся, задавай :)

2020-09-02 15:37 UTC, StealthTech commented on tests/set.js
>  'use strict';
Реализация функции предполагалась в отдельном файле в папке `source`, по аналогии с функцией `max`. Перенеси, пожалуйста

2020-09-02 15:37 UTC, StealthTech commented on tests/set.js
> +	let path = props.split(".")
В данном случае неправильно использовать let, здесь подошел бы const
Подробнее почитать можно здесь: https://learn.javascript.ru/let-const

Строки принято описывать через одинарные кавычки

2020-09-02 15:37 UTC, StealthTech commented on tests/set.js
> +const set = (object, props, val) => {
Давай добавим JSDoc? Так будет проще понимать, что происходит в функции, и что она принимает/отдаает. Подробнее можно почитать здесь: https://jsdoc.app/

2020-09-02 15:37 UTC, StealthTech commented on tests/set.js
> +		if (obj[prop] === undefined)
if лучше писать с фигурными скобками, даже если он в одну строку — улучшает читаемость

2020-09-02 15:37 UTC, StealthTech commented on tests/set.js
> +		if (idx === path.length - 1)
Кажется, что здесь нужен else if

2020-09-02 15:37 UTC, StealthTech commented on tests/set.js
> +	path.reduce((obj, prop, idx) => {
Здесь reduce ничего не возвращает. Почему бы не сделать здесь forEach?

2020-09-03 19:51 UTC, StealthTech requested changes

2020-09-03 19:51 UTC, StealthTech commented on index.html
>  <script src="source/max.js"></script>
Давай уберем отсюда max, чтобы не мешался. И тесты на него

2020-09-03 19:51 UTC, StealthTech commented on source/set.js
> +const set = (object, props, val) => {
Предлагаю заменить названия параметров: props стоило бы назвать path, т.к. это строка, и наоборот, path — скорее props, т.к. это массив. val я бы расширил до value

2020-09-03 19:51 UTC, StealthTech commented on source/set.js
> +    path.shift()
Можно заменить на slice(1) прямо в инициализации константы

2020-09-03 19:51 UTC, StealthTech commented on source/set.js
> +    let curObj = object
Я бы советовал не экономить символы, и называть более понятным образом, вроде `currentObject`

2020-09-03 19:51 UTC, StealthTech commented on source/set.js
> +	path.forEach((prop, idx) => {
Аналогично, я бы сделал prop —> property

2020-09-03 19:51 UTC, StealthTech commented on source/set.js
> +        if (curObj[prop] === undefined) {
Для таких проверок существует Object.prototype.hasOwnProperty. Подробнее можно посмотреть [здесь](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty).

Лучше проверить это так, чтобы твой код не срабатывал, если ключ существует, но при этом равен undefined

2020-09-03 19:51 UTC, StealthTech commented on source/set.js
> +		if (idx === path.length - 1) {
else нужен, т.к. иначе дважды подряд устанавливается значение curObj[prop]. Чтобы работало правильно, нужно поменять последовательность ифов, сделав этот первым. Во имя читаемости я бы вынес это условие в константу строкой выше по типу `const isLast = currentIndex === props.length - 1;`

2020-09-03 19:51 UTC, StealthTech commented on source/set.js
> +}
Нету пустой строки в конце файла. Почему их нужно оставлять: https://stackoverflow.com/a/729795/7844750

2020-09-03 19:51 UTC, StealthTech commented on source/set.js
> +	const path = props.split('.')
У тебя тут вперемешку табы и пробелы — посмотри, пожалуйста, чтобы все было в едином стиле. Многие редакторы умеют чинить это автоматически. Нпример, в Webstorm это называется "Auto-indent lines"

2020-09-05 10:09 UTC, closed without merging